//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaboxArchipelago.Patches {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParaboxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParaboxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParaboxArchipelago.Resources.ParaboxResources", typeof(ParaboxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 4
        ///#
        ///Block -1 -1 0 24 24 0.5 0.8 1 1 0 0 0 0 0 0 11
        ///	Block 0 0 25 9 9 0.2 0.65 0.55 1 0 0 0 0 0 1 0
        ///		Floor 2 3 Portal inpush_sequential_rescue
        ///		Floor 2 4 Portal inpush_poswall_priority_v3
        ///		Floor 2 7 FastTravel
        ///		Floor 4 3 Portal inpush_ref_track
        ///		Floor 4 4 Portal inpush_ref_flip
        ///		Floor 4 5 Portal inpush_intro
        ///		Floor 6 2 Portal inpush_player_is_shift
        ///		Floor 6 4 Portal inpush_navigate_inf_zone_v2
        ///		Floor 6 6 Portal inpush_no_right
        ///	Block 0 1 24 9 9 0.95 0.65 0.6 1 0 0 0 0 0 1 0
        ///		F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hub {
            get {
                return ResourceManager.GetString("hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP_Lang_Keys,EN,DE,ES,FR,KO,IT,JA,PTBR,RU,ZHCN
        ///AP_Text_Credits_Randomizer,Randomizer:,---,---,---,---,---,---,---,---,---
        ///Area_Introst,BEGIN,---,---,---,---,---,---,---,---,---.
        /// </summary>
        internal static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
    }
}
